### ISSUE TITLE
Possible typo on the landing page

### ISSUE THREAD

**Issue by MonaMayrhofer** [antares-sql/antares-website#3]
I realize that this is pretty nit picky, however this line, reads as if it meant to say "it currently supports..." instead of "it actually supports...". As it's very easy to get these two words mixed up in translation (at least in my language), yet mean wildly different things, I thought that I would drop by and give you a little heads up, in case that is indeed a mistake.

https://github.com/antares-sql/antares-website/blob/f42ef1bcfa2e80e224a865996c489a4a3a1ae124/pages/index.vue#L79

If this is not the case, I'm sorry for annoying you with such a tiny thing

Thank you for all the great work you have been doing! Cheers

**Comment by Fabio286** [comment]
You did well and I appreciate your report because I mainly read English but have never been in an English-speaking environment.

I think a lot of people don't make spelling corrections because they are worried about offending me, but I'm just happy about it.

Thank you
